using System;
using System.Collections.Generic;

namespace Hasslefree.Web.Models.Security.Sessions.Get
{
	/// <summary>
	/// Cart linked to a session
	/// </summary>
	public class SessionCart
	{
		/// <summary>
		/// Unique row identifier of the cart record
		/// </summary>
		public int CartId { get; set; }

		/// <summary>
		/// Autogenerated sequence number
		/// </summary>
		public string SeqNumber { get; set; }

		/// <summary>
		/// Cart reference
		/// </summary>
		public string Reference { get; set; }

		/// <summary>
		/// Unique Guid
		/// </summary>
		public Guid? Guid { get; set; }

		/// <summary>
		/// Base currency
		/// </summary>
		public string BaseCurrency { get; set; }

		/// <summary>
		/// Quote currency
		/// </summary>
		public string QuoteCurrency { get; set; }

		/// <summary>
		/// (Optional) Exchange rate
		/// </summary>
		public decimal? ExchangeRate { get; set; }

		/// <summary>
		/// (Optional) Discount
		/// </summary>
		public decimal? Discount { get; set; }

		/// <summary>
		/// (Optional) Total, including tax, before deductions
		/// </summary>
		public decimal? SubTotalExcl { get; set; }

		/// <summary>
		/// (Optional) Total, including tax, before deductions
		/// </summary>
		public decimal? SubTotalIncl { get; set; }

		/// <summary>
		/// (Optional) Tax amount
		/// </summary>
		public decimal? TaxAmount { get; set; }

		/// <summary>
		/// (Optional) Tax percentage
		/// </summary>
		public decimal? TaxPercentage { get; set; }

		/// <summary>
		/// (Optional) Total after deductions
		/// </summary>
		public decimal? Total { get; set; }

		/// <summary>
		/// (Optional) Items inside the cart
		/// </summary>
		public List<SessionCartLine> Items { get; set; }
	}
}
